### ISSUE TITLE
 fail to install abpred

### ISSUE THREAD

**Issue by Fang-dream** [maxhebditch/abpred#1]
Error displayed while installing dependencies
![微信图片_20200916122129](https://user-images.githubusercontent.com/58978837/93707526-12437900-fb62-11ea-9dee-fbdc4ce9d7d4.png)

**Comment by maxhebditch** [comment]
Hi, can you provide some detail about your OS and how you tried to install abpred?

**Comment by maxhebditch** [comment]
No further information
